pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r README* .public
    - cp -r index.html .public
    - cp Selection* .public
    - cp -r archive .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
